### PR TITLE
Comparison with different clustering algorithms

### PR DESCRIPTION
**Pull request by Elsword016**
Marcus, I wrote codes for different clustering algorithms. These should be used directly but have a look since I'm not good at MATLAB. DBSCAN code I pulled off file exchange but I wasn't properly able to understand the others so I wrote the implementation myself.

### CODE REVIEW

**Comment by mleiwe** [comment]
Hi Bis,
MATLAB has dbscan already
https://www.mathworks.com/help/stats/dbscan.html
Mean-Shift Clustering can also be found here, but if your version is faster feel free to use it instead
https://www.mathworks.com/matlabcentral/fileexchange/10161-mean-shift-clustering.
- Additionally in your mean-shift clustering there is no "weights" variable in the function (line 1)

Have you evaluated these codes already with dummy data?

**Comment by Elsword016** [comment]
I have calculated the weights like this,  weights = exp(-distances.^2 / (2 * bandwidth^2)); then use these weights to update the new mean. Also, no I haven't yet tried to dummy data. I was planning to do it today.

**Comment by mleiwe** [comment]
Ok, but the weights are supposed to be the magnitude of the norm mean vector not the distances between the points. Am adding the skeleton to a new branch called  "ComparingClusters" we should be able to both contribute to this branch I believe?

**Comment by Elsword016** [comment]
I see, okay I will rewrite the code, and yeah we can contribute to the main repo from the branch it self

**Comment by Elsword016** [comment]
new PR

**Pull request closed without merging**
